import { AlertTriangle } from "lucide-react";

function DisclaimerPage() {
    return (
        <div className="max-w-3xl mx-auto px-4 py-8 space-y-8">
            <h1 className="text-3xl font-bold text-slate-100">Disclaimer</h1>

            <div className="bg-slate-900/50 p-6 rounded-xl border border-slate-800 space-y-4 text-slate-300">
                <div className="flex items-center gap-2 text-amber-500 mb-4">
                    <AlertTriangle className="w-6 h-6" />
                    <span className="font-semibold text-lg">Important Notice</span>
                </div>

                <p>
                    The calculators provided on this website are for illustrative and educational purposes only.
                    They are designed to give you an estimate based on the inputs you provide.
                </p>

                <h3 className="text-lg font-semibold text-slate-100 mt-6">Not Financial Advice</h3>
                <p>
                    The results generated by these calculators do not constitute financial advice, investment advice,
                    or a recommendation to buy or sell any financial instrument. You should consult with a qualified
                    financial advisor before making any investment decisions.
                </p>

                <h3 className="text-lg font-semibold text-slate-100 mt-6">Accuracy of Data</h3>
                <p>
                    While we strive to ensure the accuracy of the calculations, we do not guarantee that the results
                    are error-free. The calculations are based on mathematical formulas and do not account for taxes,
                    exit loads, or fluctuating market conditions unless explicitly stated.
                </p>

                <h3 className="text-lg font-semibold text-slate-100 mt-6">Market Risks</h3>
                <p>
                    Investments in mutual funds and securities are subject to market risks. Past performance is not
                    indicative of future returns. The assumed rate of return in the calculators is user-defined and
                    does not guarantee actual returns.
                </p>
            </div>
        </div>
    );
}

export default DisclaimerPage;
